### PR TITLE
Scene import

### PR DESCRIPTION
**Pull request by wilderjds**
Add a template .blend file ready for importing with very basic lighting and backdrop.

The imported keyboard must be centered and rescaled to reasonable size for the lights to be working somewhat correctly; this is implemented in the first commit

### CODE REVIEW

**Comment by Kirpal** [comment]
I don't know if we should import a template for rendering. I was thinking more like a file available for download on the README, so if somebody doesn't know how to use blender they have a file to easily import and render the keyboard in.

**Comment by wilderjds** [comment]
Ok, I now uploaded the scene as a gist and linked it through the readme. You can change the wording as you deem appropriate.  I still think the keyboard should be centered, rescaled and rotated, so to make it easy to import in different scenes, so I'd stick with 310fe129b3743d9092788d5b8efe813d1fbcc1cd

**Comment by wilderjds** [comment]
Any issue with this or just busy these days?

**Comment by Kirpal** [comment]
No, I've just been busy, sorry. I've wanted to download it and test it out before I merge, and just haven't had a chance. Hopefully soon I'll test it.

**Comment by wilderjds** [comment]
Not a problem, take your time!

Cheers
 J

**Comment by Kirpal** [comment]
Finally had a chance to test it. It works great, just one bug I ran into with the LEDs, they seem to not be scaled? Picture attached:
image

**Comment by wilderjds** [comment]
On Wednesday, February 28, 2018 3:22:28 PM EST Kirpal Demian wrote:
> Finally had a chance to test it. It works great, just one bug I ran into
> with the LEDs, they seem to not be scaled? Picture attached:
> image
> 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/pull/22#issueco
> mment-369370376

Correct! I forgot about the leds. Will patch as soon as I manage.

Best
 Jacopo

**Comment by Kirpal** [comment]
Great! I'll merge it whenever you have the chance to update.

**Comment by wilderjds** [comment]
I added the leds to the empty so that they get scaled

**Comment by wilderjds** [comment]
On Wednesday, February 28, 2018 3:27:13 PM EST Kirpal Demian wrote:
> Great! I'll merge it whenever you have the chance to update.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Kirpal/Keyboard-Layout-Editor-for-Blender/pull/22#issueco
> mment-369371587

Done; please have a look
 J

**Pull request merged**
